# Generated by Django 2.2.6 on 2019-10-10 07:39

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_platform', models.CharField(db_index=True, max_length=255)),
                ('client_version', models.CharField(db_index=True, max_length=255)),
                ('client_hash', models.CharField(default=api.models.random_hash, editable=False, max_length=2500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=255)),
                ('event_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Client')),
            ],
        ),
        migrations.CreateModel(
            name='EventParam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(db_index=True, max_length=255)),
                ('param_value', models.CharField(max_length=1400)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LogEvent')),
            ],
        ),
    ]
